version: '3.8'

services:
    crypto-bot:
        build: .
        restart: unless-stopped
        env_file:
            - config.env
        volumes:
            - ./logs:/app/logs
            - ./data:/app/data # For storing persistent data
        environment:
            - ENVIRONMENT=production
            - PYTHONUNBUFFERED=1
        healthcheck:
            test: ['CMD', 'python', '-c', 'import sys; sys.exit(0)']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        networks:
            - crypto-bot-network

networks:
    crypto-bot-network:
        driver: bridge

volumes:
    logs:
    data:
